---
vagrantfile-local:
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.2.254
            forwarded_port:
                JubbwrVDzS4K:
                    host: '10000'
                    guest: '9000'
                eCXkppryd2rs:
                    host: '11000'
                    guest: '27017'
                TdncHsUJqdFu:
                    host: '12000'
                    guest: '6379'
                q5w2jdBU52sM:
                    host: '13000'
                    guest: '13000'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            gvogCRxIwT4u:
                id: vagrant-root
                source: ~/Development
                target: /var/www/vhosts
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - headers
        - php
        - rewrite
        - userdir
        - vhost_alias
    vhosts:
        ZKX2rploLUuI:
            servername: laravel.dev
            docroot: /var/www/vhosts/laravel.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
        01XcGb2hxgeH:
            servername: wordpress.dev
            docroot: /var/www/vhosts/wordpress.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
        n07mp4bVhy0D:
            servername: drupal.dev
            docroot: /var/www/vhosts/drupal.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
    mod_pagespeed: 0
    mod_spdy: 0
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - imagick
            - intl
            - mcrypt
            - memcached
            - mysql
            - odbc
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        memory_limit: 512M
        post_max_size: 512M
        max_execution_time: '120'
        upload_max_filesize: 512M
    timezone: Europe/Lisbon
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '300'
drush:
    install: '1'
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: mysqlroot
    phpmyadmin: '1'
    adminer: 0
    databases:
        MFxU47Svl7Uy:
            grant:
                - ALL
            name: laravel
            host: localhost
            user: laravel
            password: laravel
            sql_file: ''
        prwAmL1nHSse:
            grant:
                - ALL
            name: wordpress
            host: localhost
            user: wordpress
            password: wordpress
            sql_file: ''
        wIIrjkZIrxrS:
            grant:
                - ALL
            name: drupal
            host: localhost
            user: drupal
            password: drupal
            sql_file: ''
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

